export const CONTENT_DATA = [
  {
    thumbnail: "/assets/imagesThumbnail/thumbnail-1.webp",
    title: "Patroli di Kehidupan Lain | GTA Roleplay",
    username: "Raditya Dika",
    profile: "/assets/imagesProfile/profile-1.jpg",
    duration: "9.22",
    verified: true,
  },
  {
    thumbnail: "/assets/imagesThumbnail/thumbnail-2.webp",
    title: "Bikin BOT Telegram Node Js",
    username: "Dea Afrizal",
    profile: "/assets/imagesProfile/profile-2.jpg",
    duration: "36.49",
    verified: true,
  },
  {
    thumbnail: "/assets/imagesThumbnail/thumbnail-3.webp",
    title: "JADI POLISI GADUNGAN PAKE MOBIL RC POLISI - GTA 5 ROLEPLAY",
    username: "Jelool",
    profile: "/assets/imagesProfile/profile-3.jpg",
    duration: "36.58",
    verified: true,
  },
  {
    thumbnail: "/assets/imagesThumbnail/thumbnail-4.webp",
    title: "ECA MAU NYA NIKAH SAMA YANG LEBIH TUA! HABIB & DESTA KAGET!",
    username: "VINDES",
    profile: "/assets/imagesProfile/profile-4.jpg",
    duration: "24.18",
    verified: true,
  },
  {
    thumbnail: "/assets/imagesThumbnail/thumbnail-5.webp",
    title:
      "HABIB JAFAR:BUBARIN AJA NIH PODHUB!!GAK MANFAAT!!🤣VIDI-ONAD-PODHUB",
    username: "Deddy Corbuzier",
    profile: "/assets/imagesProfile/profile-5.jpg",
    duration: "1.20.21",
    verified: true,
  },
  {
    thumbnail: "/assets/imagesThumbnail/thumbnail-6.webp",
    title:
      "MAKAN NASI PADANG TERENAK DI EROPA! PER ORANG 300 RIBU?! PEDES BANGET! | WORLD TRIP",
    username: "Nihongo Mantappu",
    profile: "/assets/imagesProfile/profile-6.jpg",
    duration: "16.31",
    verified: true,
  },
  {
    thumbnail: "/assets/imagesThumbnail/thumbnail-3.webp",
    title: "TUTORIAL",
    username: "lala",
    profile: "/assets/imagesProfile/profile-7.jpg",
    duration: "10.00",
    verified: false,
  },
  {
    thumbnail: "/assets/imagesThumbnail/thumbnail-2.webp",
    title: "Bikin BOT Telegram Node Js",
    username: "Dea Afrizal",
    profile: "/assets/imagesProfile/profile-2.jpg",
    duration: "36.49",
    verified: true,
  },
  {
    thumbnail: "/assets/imagesThumbnail/thumbnail-3.webp",
    title: "JADI POLISI GADUNGAN PAKE MOBIL RC POLISI - GTA 5 ROLEPLAY",
    username: "Jelool",
    profile: "/assets/imagesProfile/profile-3.jpg",
    duration: "36.58",
    verified: true,
  },
  {
    thumbnail: "/assets/imagesThumbnail/thumbnail-4.webp",
    title: "ECA MAU NYA NIKAH SAMA YANG LEBIH TUA! HABIB & DESTA KAGET!",
    username: "VINDES",
    profile: "/assets/imagesProfile/profile-4.jpg",
    duration: "24.18",
    verified: true,
  },
  {
    thumbnail: "/assets/imagesThumbnail/thumbnail-5.webp",
    title:
      "HABIB JAFAR:BUBARIN AJA NIH PODHUB!!GAK MANFAAT!!🤣VIDI-ONAD-PODHUB",
    username: "Deddy Corbuzier",
    profile: "/assets/imagesProfile/profile-5.jpg",
    duration: "1.20.21",
    verified: true,
  },
  {
    thumbnail: "/assets/imagesThumbnail/thumbnail-6.webp",
    title:
      "MAKAN NASI PADANG TERENAK DI EROPA! PER ORANG 300 RIBU?! PEDES BANGET! | WORLD TRIP",
    username: "Nihongo Mantappu",
    profile: "/assets/imagesProfile/profile-6.jpg",
    duration: "16.31",
    verified: true,
  },
];
